[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''G.shared_shadow:draw_shader('dissolve', self.shadow_height)'''
position = "at"
payload = '''
if G.shared_shadow.aeonfish_transmute then
    G.shared_shadow:draw_shader('fac_aeonfish_transmute', self.shadow_height, self.ARGS.send_to_shader)
    self.children.center.aeonfish_transmute.image.role.draw_major = self
    self.children.center.aeonfish_transmute.image.aeonfish_transmute = {
        realtime_start = self.children.center.aeonfish_transmute.realtime_start,
        reverse = true
    }
    self.children.center.aeonfish_transmute.image:draw_shader('fac_aeonfish_transmute', self.shadow_height, self.ARGS.send_to_shader, nil, self.children.center)
else
    G.shared_shadow:draw_shader('dissolve', self.shadow_height)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''self.children.center:draw_shader('dissolve')'''
position = "at"
payload = '''
if self.ability.crimsonseraphim_starblighted then
    self.children.center:draw_shader('fac_crimsonseraphim_starblighted', nil, self.ARGS.send_to_shader)
else
    self.children.center:draw_shader('dissolve')
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = '''for k, v in pairs(SMODS.Stickers) do'''
position = "before"
payload = '''
if self.ability.crimsonseraphim_temporary then
    G.shared_stickers["crimsonseraphim_temporary"] = G.shared_stickers["crimsonseraphim_temporary"] or
    Sprite(0, 0, G.CARD_W, G.CARD_H, G.ASSET_ATLAS["fac_crimsonseraphim_temporary"], { x = 0, y = 0 })
    G.shared_stickers["crimsonseraphim_temporary"].role.draw_major = self
    G.shared_stickers["crimsonseraphim_temporary"]:draw_shader('dissolve', nil, nil, nil, self.children.center)
    G.shared_stickers["crimsonseraphim_temporary"]:draw_shader('voucher', nil, self.ARGS.send_to_shader, nil, self.children.center)
end
'''
match_indent = true
