[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS FishAndChips "src/fishminigamemechanics.lua"]'''
pattern = '''if not G.GAME.fac_active_bait then'''
position = "at"
payload = '''
if not G.GAME.fac_active_bait and not next(SMODS.find_card("fish_fac_ghost_chaosfish)) then
'''
match_indent = true
