[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# fac_reveal_catch()
# Tracking variable
[[patches]]
[patches.pattern]
target = '=[SMODS FishAndChips "/src/fishminigamemechanics.lua"]'
pattern = 'local card_limit_stalled = false'
position = 'after'
payload = '''
local anvil_kill_stalled = false
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '=[SMODS FishAndChips "/src/fishminigamemechanics.lua"]'
pattern = 'SMODS.calculate_context({fac_fish_caught = added_card, fish = profile.key, treasure = is_treasure_catch or false, perfect = state.perfect or false})'
position = 'before'
payload = '''
added_card.fac_fo_anvil = true
'''
match_indent = true
times = 1

# fac_reveal_catch()
# Causes the catch to stall if Anvil is held
[[patches]]
[patches.pattern]
target = '=[SMODS FishAndChips "/src/fishminigamemechanics.lua"]'
pattern = 'if #area.cards >= area.config.card_limit and not added_card.REMOVED then'
position = 'at'
payload = '''
local old_cond = false
-- preserve this line as a patch target
if #area.cards >= area.config.card_limit and not added_card.REMOVED then
    old_cond = true
end

if SMODS.find_card("fish_fac_fo_anvil") and not added_card.REMOVED and not added_card.tss_cheshed and added_card.fac_fo_anvil then
    G.NOT_SAFE_TO_PRESS_BUTTONS = false
    if not anvil_kill_stalled then
        anvil_kill_stalled = true
        if is_treasure_catch then
            state.fac_treasure_fish_stalled = true
        else
            state.fac_main_fish_stalled = true
        end
        fac_recompute_reward_box_shift(state)

        reward_area.config.highlight_limit = 1
        reward_area.config.highlighted_limit = 1
        
        caught_box:remove()
        caught_box = build_caught_box(#area.cards >= area.config.card_limit)
        caught_box.states.visible = true
        caught_box:juice_up()
        if discovery_text then
            discovery_text:remove()
            discovery_text = build_discovery_text()
        end
        if perfect_catch_text then
            perfect_catch_text:remove()
            perfect_catch_text = build_perfect_catch_text()
        end
        if treasure_catch_text then
            treasure_catch_text:remove()
            treasure_catch_text = build_treasure_catch_text()
        end
    end
    return false

elseif old_cond then
'''
match_indent = true
times = 1