[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if (self.OVERLAY_MENU) or (not self.F_HIDE_BG) then
'''
position = 'before'
payload = '''
FishAndChips.render_fishing_minigame()
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''
elseif self.config.type == 'play' or self.config.type == 'shop' or self.config.type == 'consumeable' then 
'''
position = 'before'
payload = '''
elseif self.config.fac_catch_area then
    card.states.drag.can = false
'''
match_indent = true