[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, atlas, pos, sprite_args)"
position = "before"
payload = '''
if _center.set == "fac_Fish" or _center.set == "fac_Bait" then
    pos = _center.pos
    atlas = _center.atlas
    sprite_args = _center.sprite_args
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "self.children.center = SMODS.create_sprite(self.T.x, self.T.y, self.T.w, self.T.h, atlas, pos, sprite_args)"
position = "after"
payload = '''
if _center.set == "fac_Fish" or _center.set == "fac_Bait" then
    if _center.pixel_size and _center.pixel_size.h and _center.unlocked and not (_center.discovered or self.bypass_discovery_center) then
        self.children.center.scale.y = self.children.center.scale.y*(_center.pixel_size.h/SMODS.get_atlas(_center.atlas).py)
    end
    if _center.pixel_size and _center.pixel_size.w and _center.unlocked and not (_center.discovered or self.bypass_discovery_center) then
        self.children.center.scale.x = self.children.center.scale.x*(_center.pixel_size.w/SMODS.get_atlas(_center.atlas).px)
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "if delay_sprites then"
position = "before"
payload = '''
if center.set == "fac_Fish" or center.set == "fac_Bait" then
    if center.display_size and center.display_size.h and center.unlocked and not (center.discovered or self.bypass_discovery_center) then
        H = H*(center.display_size.h/95)
        self.T.h = H
    elseif center.pixel_size and center.pixel_size.h and center.unlocked and not (center.discovered or self.bypass_discovery_center) then
        H = H*(center.pixel_size.h/SMODS.get_atlas(center.atlas).py)
        self.T.h = H
    end
    if center.display_size and center.display_size.w and center.unlocked and not (center.discovered or self.bypass_discovery_center) then
        W = W*(center.display_size.w/71)
        self.T.w = W
    elseif center.pixel_size and center.pixel_size.w and center.unlocked and not (center.discovered or self.bypass_discovery_center) then
        W = W*(center.pixel_size.w/SMODS.get_atlas(center.atlas).px)
        self.T.w = W
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
if card.set == 'Back' then discover_card(card) end
'''
position = 'before'
payload = '''
if card.set == 'fac_Rod' then discover_card(card); check_for_unlock({ type = 'fac_rod_unlocked'}) end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "=[SMODS _ \"src/card_draw.lua\"]"
pattern = '''
if self.edition then 
'''
position = 'before'
payload = '''
if self.config.center.set == "fac_Fish" or self.config.center.set == "fac_Bait" then
    if not self.config.center.discovered and (self.config.center.unlocked or self.area and self.area.config.fac_compendium) then
        self.children.floating_sprite:draw_shader('fac_hide_fish', nil, self.ARGS.send_to_shader, nil, self.children.center, scale_mod, rotate_mod)
    else
        local fish_data = G.PROFILES[G.SETTINGS.profile].fac_fishing.fish_data[self.config.center_key] or {}
		if not (fish_data.times_caught and fish_data.times_caught > 0) and self.area and self.area.config.fac_compendium then
            self.children.floating_sprite:draw_shader('fac_hide_fish', nil, self.ARGS.send_to_shader, nil, self.children.center, scale_mod, rotate_mod)
        end
    end
end
'''
match_indent = true
times = 1
