[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
pattern = '''for _, v in ipairs(info_queue) do'''
position = 'before'
payload = '''
if SMODS.find_card("fish_fac_proto_noir")[1] then noirFish = SMODS.find_card("fish_fac_proto_noir")[1] end
if card and SMODS.is_playing_card(card) and card.ability.noir_mark and card.ability.noir_level then info_queue[#info_queue+1] = { key = "proot_noir_doors", vars = { ((localize("proot_noir_"..card.ability.noir_mark)) or " "), card.ability.noir_level - noirFish.ability.extra.nearest_starter_level[noirFish.ability.extra.level] }, set = "Other" } end
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
pattern = '''for _, v in ipairs(info_queue) do'''
position = 'before'
payload = '''
if card and SMODS.is_playing_card(card) and card.ability.noir_mark then info_queue[#info_queue+1] = { key = "proot_noir_"..card.ability.noir_mark, set = "Other" } end
'''
